Algoritmo "L03B"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Obama
// Descrição   : Um algoritmo que cálcula o total da soma obtida dos cem primeiros números inteiros.
// Autor(a)    : Ian Guimarães Silva
// Data atual  : 06/04/2025
Var
   // Seção de Declarações das variáveis

   i, soma: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 1
   soma <- 0
   enquanto i <= 100 faca
      soma <- soma + i
      i <- i + 1
   fimenquanto
   escreval("A soma dos 100 primeiros números inteiros é: ", soma)

Fimalgoritmo