Algoritmo "L03D"
// Disciplina  : [Lógica de Programação com Javascript]
// Professor   : Obama
// Descrição   : Um algoritmo que calcula os números ímpares de 1 até 20.
// Autor(a)    : Ian Guimarães Silva
// Data atual  : 06/04/2025

Var
   // Seção de Declarações das variáveis
   i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 1

   enquanto i <= 20 faca
      escreval(i)
      i <- i + 2
   fimenquanto

Fimalgoritmo